<?php

namespace Phpteda\Util;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-10 at 20:04:13.
 */
class ChoiceTest extends \PHPUnit_Framework_TestCase
{
    public function testReturningFirstValueWhenConditionTrue()
    {
        $expectedValue = 'val1';
        $actualValue = Choice::when(true)->then('val1')->otherwise('val2');
        $this->assertEquals($expectedValue, $actualValue);
    }

    public function testReturningSecondValueWhenConditionFalse()
    {
        $expectedValue = 'val2';
        $actualValue = Choice::when(false)->then('val1')->otherwise('val2');
        $this->assertEquals($expectedValue, $actualValue);
    }

    public function testReturningAValueWhenConditionTrueOtherwiseNull()
    {
        $this->assertNull(Choice::when(false)->thenReturn('val1'));

        $expectedValue = 'val1';
        $actualValue = Choice::when(true)->thenReturn('val1');
        $this->assertEquals($expectedValue, $actualValue);
    }

    public function testReturningConditionValueWhenNotFalseOrOtherwiseValue()
    {
        $expectedValue = 'val1';
        $actualValue = Choice::when('val1')->otherwise('val2');
        $this->assertEquals($expectedValue, $actualValue);
    }
}
