<?php

namespace Phpteda\Reflection;

use Doctrine\Common\Annotations\AnnotationReader;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-11 at 23:13:04.
 */
class MethodRetrieverTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers Phpteda\Reflection\MethodRetriever::getAllPublicMethods
     * @todo   Implement testGetAllPublicMethods().
     */
    public function testGetAllPublicMethods()
    {
        $class = new \ReflectionClass('\Phpteda\Generator\DummyGenerator');
        $reader = new AnnotationReader();

        $retriever = new MethodRetriever($class, $reader);

//        var_dump($retriever->getMethods(\ReflectionMethod::IS_PUBLIC));
            var_dump($retriever->getMagicMethods());

    }
}
