<?php

namespace Phpteda\Test\Reflection;

use Phpteda\Reflection\ClassAnnotationReader;
use Phpteda\Test\Reflection\TestClassForAnnotations;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-12 at 16:27:44.
 */
class ClassAnnotationReaderTest extends \PHPUnit_Framework_TestCase
{
    public function testRetrievingAnnotations()
    {

    }


    public static function provideMagicMethodStrings()
    {
        return array(
            'complete' => array(
                'bool isValid(Form $form) Checks form object',
                'bool,isValid,Form,form,Checks form object'
            ),
            'without return-type' => array(
                'isValid(Form $form) Checks form object',
                ',isValid,Form,form,Checks form object'
            ),
            'without parameter' => array(
                'string getName() Returns name',
                'string,getName,,,Returns name'
            ),
            'without description' => array(
                'string getName()',
                'string,getName,,,'
            ),
            'with many spaces' => array(
                ' bool  isValid(Form $form)  Checks form object ',
                'bool,isValid,Form,form,Checks form object'
            )
        );
    }

    /**
     * @dataProvider provideMagicMethodStrings
     */
    public function testParseMagicMethodAnnotation($methodString, $expectedString)
    {
        $classReader = new ClassAnnotationReader(
            new \ReflectionClass('Phpteda\Test\Reflection\TestClassForAnnotations')
        );
        $methodParts = $classReader->parseMagicMethodAnnotation($methodString);
        $actualString = implode(',', $methodParts);

        $this->assertEquals($expectedString, $actualString);
    }
}