<?php

namespace Phpteda\Test\Reflection;

use Mockery;
use Phpteda\Reflection\MethodRetriever;
use Phpteda\Reflection\Method;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-11 at 23:13:04.
 */
class MethodRetrieverTest extends \PHPUnit_Framework_TestCase
{
    /** @var \Mockery\MockInterface | ReflectionClass */
    protected $reflectionClass;

    /** @var \Mockery\MockInterface | \Phpteda\Reflection\ClassAnnotationReader */
    protected $annotationReader;


    protected function setUp()
    {
        $this->reflectionMethod = Mockery::mock('\ReflectionMethod')->shouldIgnoreMissing();
        $this->reflectionMethod->shouldReceive('getName')->andReturn('nameOfMethod');
        $this->reflectionMethod->shouldReceive('getParameters')->andReturn(array('nameOfParameter'));

        $this->reflectionClass = Mockery::mock('\ReflectionClass')->shouldIgnoreMissing();
        $this->reflectionClass->shouldReceive('getMethods')->andReturn(array($this->reflectionMethod));

        $this->annotationReader = Mockery::mock('\Phpteda\Reflection\ClassAnnotationReader')->shouldIgnoreMissing();
        $this->annotationReader
            ->shouldReceive('setReflectionClass->getAnnotations')
            ->andReturn(array('method' => 'method string foo'));
        $this->annotationReader->shouldReceive('parseMagicMethodAnnotation')->andReturn(
            array(
                'returnType' => 'returnType',
                'name' => 'magicMethodName',
                'parameterType' => 'parameterType',
                'parameterName' => 'parameterName',
                'description' => 'description'
            )
        );
    }

    protected function tearDown()
    {
        Mockery::close();
    }


    public function testGetAllPublicMethods()
    {
        $retriever = new MethodRetriever(
            $this->reflectionClass,
            $this->annotationReader
        );

        $actualMethods = $retriever->getAllPublicMethods();

        $expectedMethods = array(
            new Method(
                array(
                    'returnType' => 'returnType',
                    'name' => 'magicMethodName',
                    'parameterType' => 'parameterType',
                    'parameterName' => 'parameterName',
                    'description' => 'description'
                )
            ),
            new Method(
                array(
                    'returnType' => null,
                    'name' => 'nameOfMethod',
                    'parameterType' => null,
                    'parameterName' => 'nameOfParameter',
                    'description' => null
                )
            )
        );

        $this->assertEquals($expectedMethods, $actualMethods);
    }


    public function testFilteringOfIgnoredMethods()
    {
        $this->markTestIncomplete();
    }
}
