<?php

namespace Phpteda\Test\Generator;

use Phpteda\Generator\Options;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-09 at 17:56:31.
 */
class OptionsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Options
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Options;
    }

    public function testSetBooleanOption()
    {
        $this->object->setBooleanOption('testOpt');
        $this->assertTrue($this->object->getOption('testOpt'));
    }

    public function testSetOption()
    {
        $this->object->setOption('testOpt', 'value');
        $this->assertEquals('value', $this->object->getOption('testOpt'));
    }

    public function testHasOption()
    {
        $this->assertFalse($this->object->hasOption('testOpt'));
        $this->object->setOption('testOpt', 'value');
        $this->assertTrue($this->object->hasOption('testOpt'));
    }

    public function testGettingNotExistingOption()
    {
        $this->assertNull($this->object->getOption('testOpt'));
    }
}
