<?php
namespace Phpteda\Generator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-09 at 17:56:31.
 */
class OptionsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Options
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Options;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Phpteda\Generator\Options::setBooleanOption
     * @todo   Implement testSetBooleanOption().
     */
    public function testSetBooleanOption()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phpteda\Generator\Options::setOption
     * @todo   Implement testSetOption().
     */
    public function testSetOption()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phpteda\Generator\Options::hasOption
     * @todo   Implement testHasOption().
     */
    public function testHasOption()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phpteda\Generator\Options::getOption
     * @todo   Implement testGetOption().
     */
    public function testGetOption()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
