@startuml


class Configuration.Property {

}

class Configuration.Selection {

}

class Configuration.Group {

}

class GeneratorConfigurator {
    createByGeneratorClassName($className):GeneratorConfigurator
    createByGeneratorPathname($pathname):GeneratorConfigurator
    getConfigurationProperties():Property[]
    getConfiguredGenerator():GeneratorInterface
}

class Generator {
    getConfig():string
}


XMLReader <|-- ConfigReader

class XMLReader {
}

class ConfigReader {
isGroup()
isBoolean()
isProperty()
isChoice()
isDecision()
}





@enduml